din-im-liau/Controllers/OrderController.cs
using Models.Attributes;
using Models.Requests;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace din_im_liau.Controllers;


[SwaggerTag("團購單")]
public class OrderController : BaseController
{

    /// <summary>
    /// 團購單列表
    /// </summary>
    /// <param name="condition">條件</param>
    /// <returns></returns>
    [HttpPost("list")]
    public async Task<IActionResult> List([FromBody] BaseConditionRequest condition)
    {
        return Ok(new { condition });
    }

    /// <summary>
    /// 取得團購單資料
    /// </summary>
    /// <param name="id">團購單id</param>
    /// <returns></returns>
    [HttpGet("detail/{id}")]
    public async Task<IActionResult> Detail(int id)
    {
        return Ok(new { id });
    }

    /// <summary>
    /// 產生該筆團購單的統計報表
    /// </summary>
    /// <returns></returns>
    [HttpPost("sheet")]
    public async Task<IActionResult> Sheet([FromBody] BaseIdRequest request)
    {
        return Ok(request);
    }


    /// <summary>
    /// 建立一筆新的團購單
    /// </summary>
    /// <param name="request"></param>
    /// <returns></returns>
    [HttpPost("create")]
    public async Task<IActionResult> Create([FromBody] BaseIdRequest request)
    {
        return Ok(new { request });
    }

    /// <summary>
    /// 關閉團購單
    /// </summary>
    /// <param name="request">團購單id</param>
    /// <returns></returns>
    [HttpPost("close")]
    public async Task<IActionResult> Close([FromBody] BaseIdRequest request)
    {
        return Ok(new { request });
    }

    /// <summary>
    /// 刪除團購單
    /// </summary>
    /// <param name="request">團購單名稱</param>
    /// <returns></returns>
    [HttpDelete("delete")]
    [SwaggerSuccessResponse]
    public async Task<IActionResult> Delete([FromBody] BaseIdRequest request)
    {
        return Ok(new { request });
    }

    /// <summary>
    /// 刪除團購單內一筆飲料
    /// </summary>
    /// <param name="request">飲料</param>
    /// <returns></returns>
    [HttpDelete("record/remove")]
    [SwaggerSuccessResponse]
    public async Task<IActionResult> RemoveRecord([FromBody] BaseIdRequest request)
    {
        return Ok(new { request });
    }

    /// <summary>
    /// 加入飲料到團購單
    /// </summary>
    /// <param name="request">飲料資料</param>
    /// <returns></returns>
    [HttpPost("record/create")]
    public async Task<IActionResult> CreateRecord([FromBody] BaseIdRequest request)
    {
        return Ok(new { request });
    }


    /// <summary>
    /// 更新內容品項
    /// </summary>
    /// <param name="request">品項</param>
    /// <returns></returns>
    [HttpPut("record/update")]
    public async Task<IActionResult> UpdateRecord([FromBody] BaseIdRequest request)
    {
        return Ok(new { request });
    }
}

din-im-liau/Controllers/User/GoogleController.cs
using Microsoft.AspNetCore.Mvc;

namespace din_im_liau.Controllers.Login;

[Route("user/google2")]
public class Google2Controller : ControllerBase
{
    private HttpContext _httpContext;
    public Google2Controller(IHttpContextAccessor httpContextAccessor)
    {
        _httpContext = httpContextAccessor.HttpContext!;
    }
    [Route("")]
    [HttpPost]
    public IActionResult Index()
    {
        Console.WriteLine(_httpContext.Request.Cookies);
        return new JsonResult(new { controller = true });
    }
}

din-im-liau/Controllers/User/TestEndpointController.cs
using Microsoft.AspNetCore.Mvc;

namespace din_im_liau.Controllers.User;

[Route("test")]
[Produces("application/json")]

[ApiController]
public class TestEndpointController : ControllerBase
{

    public TestEndpointController()
    {
        Console.WriteLine("init test endpoint");
    }

    [HttpGet("test2")]
    public async Task<IActionResult> Index([FromQuery] TestRequest param)
    {
        Console.WriteLine(param);
        return Ok(new { result = "ok" });
    }

    [HttpPost("post1")]
    public async Task<IActionResult> Post1()
    {
        return Ok(new { result = "post1" });
    }

    [HttpPost("post2")]
    public async Task<IActionResult> Post2()
    {
        return Ok(new { result = "post2" });
    }

    [HttpGet("get2")]
    public async Task<IActionResult> Get2()
    {
        return Ok(new { result = "get2" });
    }

    [HttpGet("get3")]
    public async Task<IActionResult> Get3([FromQuery] TestRequest req)
    {
        return Ok(req);
    }

    [HttpPost("post3")]
    public async Task<IActionResult> Post3([FromForm] TestRequest req)
    {
        return Ok(req);
    }
}

din-im-liau/Controllers/UserController.cs
using Models.Attributes;
using Models.Requests;
using Microsoft.AspNetCore.Mvc;
using Models.DTOs;
using Models.Responses;
using Services;
using Swashbuckle.AspNetCore.Annotations;
using Microsoft.AspNetCore.Authorization;
using Models.Exceptions;
using Microsoft.AspNetCore.Http.HttpResults;
using din_im_liau.Middlewares;

namespace din_im_liau.Controllers;


[SwaggerTag("會員")]
public class UserController : BaseController
{

    private readonly AccountService AccountService;

    public UserController(AccountService accountService)
    {
        AccountService = accountService;
    }
    /// <summary>
    /// 會員資料 by id
    /// </summary>
    /// <param name="id">會員id</param>
    /// <returns></returns>
    [HttpGet("profile/{id}")]
    public async Task<IActionResult> ProfileById(int id)
    {

        return Ok(new { Id = id });
    }

    /// <summary>
    /// 會員資料 by token
    /// </summary>
    /// <returns></returns>
    [HttpGet("profile")]
    [SwaggerSuccessResponse(typeof(GenericResponse<AccountDTO>))]
    public async Task<IActionResult> Profile()
    {

        var currentAccountId = Account?.Id ?? throw new NotFoundException(" user not found");
        var currentAccount = await AccountService.GetAccountDTOById(currentAccountId) ?? throw new NotFoundException(" user not found");

        Response200.Data = currentAccount;

        return Ok(Response200);
    }

    /// <summary>
    /// 更新會員資料
    /// </summary>
    /// <param name="body">會員內容</param>
    /// <returns></returns>
    [HttpPut("profile")]
    [SwaggerSuccessResponse(typeof(GenericResponse<AccountDTO>))]
    public async Task<IActionResult> UpdateProfile([FromBody] UpdateProfileRequest body)
    {
        Response200.Data = await AccountService.UpdateAccount(Account.Id, body);
        return Ok(Response200);
    }


    /// <summary>
    /// 會員列表
    /// </summary>
    /// <param name="condition">列表條件</param>
    /// <returns></returns>
    [AuthorizeRoleAdmin]
    [HttpPost("list")]
    public async Task<IActionResult> List([FromBody] UserListRequest condition)
    {
        return Ok(condition);
    }

    /// <summary>
    /// 追蹤商店
    /// </summary>
    /// <param name="id">商店id</param>
    /// <returns></returns>

    [HttpPost("shop/follow")]
    public async Task<IActionResult> Follow([FromForm] string id)
    {
        return Ok(Account);
    }

    /// <summary>
    /// 列出已追蹤商店
    /// </summary>
    /// <returns></returns>

    [HttpGet("shop/following")]
    public async Task<IActionResult> Following([FromBody] BaseConditionRequest condition)
    {
        return Ok(condition);
    }


}

din-im-liau/Pages/Login/Google.cshtml.cs
using System.Text.Json;
using System.Text.Json.Serialization;
using din_im_liau.Page;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.ObjectPool;
using Services.Helper;
using Common.Extensions;
using Services;

namespace din_im_liau.Pages.Login;

public class GoogleOAuthResponse
{
    public string state { get; set; }
    public string code { get; set; }
    public string hd { get; set; }

}

public partial class Oauth2GoogleTokenResponse
{
    [JsonPropertyName("access_token")]
    public string AccessToken { get; set; }

    [JsonPropertyName("expires_in")]
    public long ExpiresIn { get; set; }

    [JsonPropertyName("refresh_token")]
    public string RefreshToken { get; set; }

    [JsonPropertyName("scope")]
    public Uri Scope { get; set; }

    [JsonPropertyName("token_type")]
    public string TokenType { get; set; }

    [JsonPropertyName("id_token")]
    public string IdToken { get; set; }
}

public class GoogleViewModel
{
    public string email { get; set; }
    public string fullName { get; set; }
    public string thumbnailUrl { get; set; }

    public string googleUserId { get; set; }
}
[AllowAnonymous]
public class GoogleModel : BasePageModel
{

    private AccountService AccountService { get; set; }

    public GoogleViewModel GoogleViewModel { get; set; }

    private IConfiguration _config;
    public GoogleModel(AccountService accountService, IConfiguration config, IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
    {
        _config = config;
        AccountService = accountService;
    }
    public async Task<IActionResult> OnGet([FromQuery] GoogleOAuthResponse response)
    {
        if (!_httpContext.IsGoogleStateTokenValid(response.state))
        {
            return new RedirectToPageResult("/User/LoginError");
        }
        Console.WriteLine(response.ToString());
        var client = new HttpClient();
        client.BaseAddress = new Uri("https://oauth2.googleapis.com");

        var formData = new Dictionary<string, string>();
        formData.Add("client_id", _config["Google:ClientId"] ?? "");
        formData.Add("client_secret", _config["Google:ClientSecret"] ?? "");
        formData.Add("code", response.code);
        formData.Add("grant_type", "authorization_code");
        formData.Add("redirect_uri", "https://localhost:8888/login/google");

        using var authCodeResponse = await client.PostAsync("token", new FormUrlEncodedContent(formData));
        var responseBody = await authCodeResponse.Content.ReadAsStringAsync();

        var oauth2GoogleTokenResponse = JsonSerializer.Deserialize<Oauth2GoogleTokenResponse>(responseBody);



        var model = JwtHelper.contertToGooglePayload(oauth2GoogleTokenResponse?.IdToken ?? "");

        Console.WriteLine(model.Email);

        //RedirectToPage("GoogleVerifyToken");

        var vm = new GoogleViewModel
        {
            email = model.Email ?? "",
            fullName = model.GivenName ?? "" + model.FamilyName ?? "",
            googleUserId = model.Sub ?? "",
            thumbnailUrl = model.Picture ?? ""
        };
        var lastAccount = await AccountService.Get(vm.googleUserId);
        if (lastAccount == null)
        {
            var result = await AccountService.Create(vm.googleUserId, vm.fullName, vm.email, vm.thumbnailUrl);
            await SignIn(result.GoogleOpenId, result.Id.ToString());
        }
        else {
            await SignIn(lastAccount.GoogleOpenId, lastAccount.Id.ToString());
        }
        
        GoogleViewModel = vm;

        var directPage = new RedirectToPageResult("/user/profile");
        var directPage2 = LocalRedirect("/user");
        return directPage2;
    }

    public async Task<IActionResult> OnPost([FromBody] object payload)
    {
        Console.WriteLine(payload);
        return Page();

    }
}

din-im-liau/Pages/Login/GoogleVerifyToken.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace din_im_liau.Pages.Login;

public class GoogleVerifyTokenModel : PageModel
{

    public async Task<IActionResult> OnGet()
    {
        Console.WriteLine("OnGet");
        return Page();
    }

    public async Task<IActionResult> OnPost()
    {
        Console.WriteLine("OnPost");
        return Page();
    }
}

din-im-liau/Pages/Login/Index.cshtml.cs
using Azure;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Web;
namespace din_im_liau.Pages.Login;
public class IndexModel : PageModel
{
    private readonly IConfiguration _config;
    public IndexModel(IConfiguration config)
    {
        _config = config;
    }
    public async Task<IActionResult> OnGet()
    {
        Console.WriteLine("get");
        return Page();
    }

    public async Task<IActionResult> OnGetGoogleSignIn()
    {
        var uriBuilder = new UriBuilder("https", "accounts.google.com");
        uriBuilder.Path = "/o/oauth2/v2/auth";
        var parameters = new Dictionary<string, string>();

        parameters.Add("state", "eyJjc3JmVG9rZW4iOiI1YmEwY2E5NzRjNTJkNzA3ZTYzY2Y3ODkzY2ExODQ3NjIzZTA5NmNmMmQxZDg4NGJlNzEyMzVkMjMzOGI0OWY1IiwiYW5vbnltb3VzSWQiOiJhMjZlYTEyZS0zYzhlLTQyN2EtYTBkNy1hZjcyMTBhYTg2MDkiLCJxdWVyeSI6Ij9hcHBsaWNhdGlvbj1iaXRidWNrZXQmY29udGludWU9aHR0cHMlM0ElMkYlMkZiaXRidWNrZXQub3JnJTJGYWNjb3VudCUyRnNpZ25pbiUyRiUzRm5leHQlM0QlMjUyRiUyNnJlZGlyZWN0Q291bnQlM0QxJmxvZ2luVHlwZT1nb29nbGVCdXR0b24mcHJvbXB0PXNlbGVjdF9hY2NvdW50JnNvdXJjZT1sb2dpblNjcmVlbiIsInNvdXJjZSI6ImxvZ2luU2NyZWVuIiwibG9naW5UeXBlIjoiZ29vZ2xlQnV0dG9uIn0%3D");
        var clientId = _config["Google:ClientId"] ?? "";
        parameters.Add("access_type", "offline");
        parameters.Add("scope", "openid email profile");
        parameters.Add("response_type", "code");
        parameters.Add("redirect_uri", "https://localhost:8888/login/google");
        parameters.Add("client_id", clientId);
        parameters.Add("prompt", "select_account");
        var queryBuilder = new QueryBuilder(parameters);
        QueryString queryString = queryBuilder.ToQueryString();
        uriBuilder.Query = queryString.Value;
        var result = uriBuilder.Uri.AbsoluteUri;


        Console.WriteLine("get sign in");
        return Redirect(result);
    }


    public async Task<IActionResult> OnPost()
    {
        Console.WriteLine("post");
        return Page();
    }

    public async Task<IActionResult> OnPostGoogleSignIn()
    {
        Console.WriteLine("post google sign in");
        return Page();
    }
}

din-im-liau/Pages/User/Google.cshtml.cs
using din_im_liau.Page;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace din_im_liau.Pages.User;
[AllowAnonymous]
[IgnoreAntiforgeryToken(Order = 1001)]
public class GoogleModel(IHttpContextAccessor httpContextAccessor) : BasePageModel(httpContextAccessor)
{
    public async Task<IActionResult> OnPost()
    {
        return new JsonResult(new { Success = true });

    }
}

din-im-liau/Pages/User/Index.cshtml.cs
using Amazon;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace din_im_liau.Pages.User;
public class IndexModel : PageModel {
    public IndexModel(){}

    public IActionResult OnGet() {
        return new RedirectToPageResult("/user/profile");
    }
}

din-im-liau/Pages/User/Login.cshtml.cs
using Azure;
using din_im_liau.Page;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Web;
using Common.Extensions;
using Common.Helper;
namespace din_im_liau.Pages.User;

[AllowAnonymous]
[IgnoreAntiforgeryToken(Order = 1001)]
public class LoginModel : BasePageModel
{
    private readonly IConfiguration _config;
    public LoginModel(IConfiguration config, IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
    {
        _config = config;
    }
    public async Task<IActionResult> OnGet()
    {
        _httpContext.DeleteGoogleState();
        Console.WriteLine("get");
        return Page();
    }

    public async Task<IActionResult> OnGetGoogleSignIn()
    {
        var uriBuilder = new UriBuilder("https", "accounts.google.com");
        uriBuilder.Path = "/o/oauth2/v2/auth";
        var parameters = new Dictionary<string, string>();
        var oauthState = RandomHelper.Random(32) ?? "state_token";
        _httpContext.SetGoogleStateResponseCookie(oauthState);

        parameters.Add("state", oauthState);
        var clientId = _config["Google:ClientId"] ?? "";
        parameters.Add("access_type", "offline");
        parameters.Add("scope", "openid email profile");
        parameters.Add("response_type", "code");
        parameters.Add("redirect_uri", "https://localhost:8888/login/google");
        parameters.Add("client_id", clientId);
        parameters.Add("prompt", "select_account");
        var queryBuilder = new QueryBuilder(parameters);
        QueryString queryString = queryBuilder.ToQueryString();
        uriBuilder.Query = queryString.Value;
        var result = uriBuilder.Uri.AbsoluteUri;


        Console.WriteLine("get sign in");
        return Redirect(result);
    }


    public async Task<IActionResult> OnPostAsync()
    {

        Console.WriteLine("post");
        return new JsonResult(new { Success = true, });
    }
    public async Task<IActionResult> OnPostGoogleSignIn()
    {
        Console.WriteLine("post google sign in");
        return Page();
    }
}

din-im-liau/Pages/User/Logout.cshtml.cs
using din_im_liau.Page;
using Microsoft.AspNetCore.Mvc;

namespace din_im_liau.Pages.User;

public class LogoutModel : BasePageModel
{
    public LogoutModel(IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor) { }

    public async Task<IActionResult> OnGet()
    {
        await SignOut();
        return new RedirectToPageResult("/Index");
    }
}

din-im-liau/Pages/User/Orders.cshtml.cs
using din_im_liau.Page;
using Microsoft.AspNetCore.Mvc;

namespace din_im_liau.Pages.User;
public class OrdersModel(IHttpContextAccessor httpContextAccessor) : BasePageModel(httpContextAccessor)
{
    public async Task<IActionResult> OnGet()
    {
        return Page();
    }
}

din-im-liau/Pages/User/Google.cshtml
@page
@model din_im_liau.Pages.User.GoogleModel;

din-im-liau/Pages/User/Index.cshtml
@page
@model din_im_liau.Pages.User.IndexModel;
@{

}

din-im-liau/Pages/User/Login.cshtml
@page
@model din_im_liau.Pages.User.LoginModel;
@{
  Layout = null;
}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  @* <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors"> *@
  @* <meta name="generator" content="Hugo 0.88.1"> *@
  <title>Sign In</title>

  @* <link rel="canonical" href="https://bootstrap5.hexschool.com/docs/5.1/examples/sign-in/"> *@


  <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />


  <!-- Bootstrap core CSS -->

  <!-- Favicons -->
  @* <link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
  <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
  <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
  <link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
  <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
  <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico"> *@
  <meta name="theme-color" content="#7952b3">


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    html,
    body {
      height: 100%;
    }

    body {
      display: flex;
      align-items: center;
      padding-top: 40px;
      padding-bottom: 40px;
      background-color: #f5f5f5;
    }

    .form-signin {
      width: 100%;
      max-width: 330px;
      padding: 15px;
      margin: auto;
    }

    .form-signin .checkbox {
      font-weight: 400;
    }

    .form-signin .form-floating:focus-within {
      z-index: 2;
    }

    .form-signin input[type="email"] {
      margin-bottom: -1px;
      border-bottom-right-radius: 0;
      border-bottom-left-radius: 0;
    }

    .form-signin input[type="password"] {
      margin-bottom: 10px;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
    }


    @@media(min - width:768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

  <script src="https://accounts.google.com/gsi/client" async></script>

  <script>

    function handleCredentialResponse(response) {
      // decodeJwtResponse() is a custom function defined by you
      // to decode the credential response.
      console.log(response);
      alert(response.credential);

      const responsePayload = decodeJwtResponse(response.credential);

      console.log("ID: " + responsePayload.sub);
      console.log('Full Name: ' + responsePayload.name);
      console.log('Given Name: ' + responsePayload.given_name);
      console.log('Family Name: ' + responsePayload.family_name);
      console.log("Image URL: " + responsePayload.picture);
      console.log("Email: " + responsePayload.email);
    }
  </script>
  <!-- Custom styles for this template -->
</head>

<body class="text-center">

  <main class="form-signin">

    <img class="mb-4" src="~/assets/pokemon-logo.png" alt="" width="100" height="100">
    <h1 class="h3 mb-3 fw-normal">請使用 Google 帳號登入</h1>


    @* <div id="g_id_onload" data-client_id="697611657905-ide2j8m6bav95l0kcn45kn1lra6c7v3l.apps.googleusercontent.com"
    data-context="signin" data-ux_mode="popup" data-callback="handleCredentialResponse" data-auto_prompt="false">
    </div>

    <div class="g_id_signin" data-type="standard" data-shape="pill" data-theme="filled_black" data-text="continue_with"
    data-size="large" data-locale="zh-TW" data-logo_alignment="right" data-width="300">
    </div> *@


    <form>
      <a class="btn btn-primary btn-lg" role="button" asp-page-handler="GoogleSignIn">Sign In With Google </a>
      @* <button class="btn btn-primary btn-lg" role="button" asp-page-handler="GoogleSignInButton">Google Sign In
      Post</button> *@
    </form>



    <p class="mt-5 mb-3 text-muted">&copy; 2024</p>

  </main>



</body>

</html>

din-im-liau/Pages/User/LoginError.cshtml
@page
<div>
  <p>Login Error!</p>
  <p>Please Try Again!</p>
</div>

din-im-liau/Pages/User/Logout.cshtml
@page
@model din_im_liau.Pages.User.LogoutModel;

din-im-liau/Pages/User/Orders.cshtml
@page
@model din_im_liau.Pages.User.GoogleModel;

<div class="text-center">
  Orders!
</div>

din-im-liau/Pages/User/Profile.cshtml
@page
@model din_im_liau.Pages.User.ProfileModel;

@{
  ViewData["Title"] = "會員資料";
  

}
<div class="text-left">

  <form method="post" enctype="multipart/form-data">
    <fieldset>
      <legend>使用者資料設定</legend>
      @* @Html.HiddenFor(model => model.ProfileVM.Email) *@
      <div class="mb-3">
        <div>
            <div class="justify-content-center mb-4">
                <img id="selectedAvatar" src="@Model.ProfileVM.AvatarUrl"
                class="rounded-circle" style="width: 150px; height: 150px; object-fit: cover;" alt="example placeholder" />
            </div>
            <div class="justify-content-center">
                <div data-mdb-ripple-init class="btn btn-primary btn-rounded">
                    <label class="form-label text-white m-1" for="customFile2">選擇圖片</label>
                    <input type="file" asp-for="@Model.Upload" class="form-control d-none" id="customFile2" onchange="displaySelectedImage(event, 'selectedAvatar')" />
                </div>
            </div>
        </div>
      </div>
      <div class="mb-3">
        <label asp-for=ProfileVM.Email class="form-label"></label>
        <input asp-for="ProfileVM.Email" class="form-control" disabled>
        @Html.ValidationMessageFor(model => model.ProfileVM.Email, "", new { @class = "text-danger" })
      </div>
      <div class="mb-3">
        <label asp-for=@Model.ProfileVM.NickName class="form-label"></label>
        @* <input asp-for=@Model.ProfileVM.NickName placeholder="@Html.DisplayNameFor(m => m.ProfileVM.NickName)"
          class="form-control"> *@

        @Html.TextBoxFor(m => m.ProfileVM.NickName, new { @class = "form-control", placeholder = "@Html.DisplayNameFor(m => m.ProfileVM.NickName)" })
        @Html.ValidationMessageFor(model => model.ProfileVM.NickName, "", new { @class = "text-danger" })

      </div>
      @* <div class="mb-3">
      <label for="disabledSelect" class="form-label">Disabled select menu</label>
      <select id="disabledSelect" class="form-select">
      <option>Disabled select</option>
      </select>
      </div>
      <div class="mb-3">
      <div class="form-check">
      <input class="form-check-input" type="checkbox" id="disabledFieldsetCheck" disabled>
      <label class="form-check-label" for="disabledFieldsetCheck">
      Can't check this
      </label>
      </div>
      </div> *@
      <button type="submit" class="btn btn-primary">儲存</button>
    </fieldset>
  </form>
</div>
@* <div class="text-center">



<div class="card" style="width: 18rem;">
<div class="rounded-circle border border-5">
<img src="@Url.Content(Model.GoogleViewModel.thumbnailUrl)" class="card-img-top " alt="pic">
</div>

<div class="card-body">
<p>@Html.DisplayFor(modelItem => modelItem.GoogleViewModel.email)</p>
<p>@Html.DisplayFor(modelItem => modelItem.GoogleViewModel.fullName)</p>
<p>@Html.DisplayFor(modelItem => modelItem.GoogleViewModel.googleUserId)</p>
</div>
</div>
</div> *@

@section Scripts {
    <script>
      console.log('profile');
        function displaySelectedImage(event, elementId) {
        const selectedImage = document.getElementById(elementId);
        const fileInput = event.target;

        if (fileInput.files && fileInput.files[0]) {
            const reader = new FileReader();

            reader.onload = function(e) {
                selectedImage.src = e.target.result;
            };

            reader.readAsDataURL(fileInput.files[0]);
        }
      }
    </script>
}